<?php if($data->getThreadsLength() < 1): ?>
    <p>TODO infomessage</p>
<?php endif; ?>

<?php 
$page = getPageIndex();
?>

<?php if ($page < 1 || $page > $data->getMaxPages()): ?>
    <p>TODO errormessages</p>
<?php endif; ?>

<?php 

$threads = $data->getThreads();
?>

<?php foreach($threads as $thread): ?>

    <?php
    $creator = $thread->getCreator();
    $lastAttr = $thread->getLastAttributor();
    $pags = $data->getStartEndPags(
        $thread,
        $data->getThreadlinkPaginationInterval()
    );
    ?>

    <div class="forum_content_listitem forum_thread">
        <a href="<?= Web\pagelinkForumThread($thread->getPrimaryKey(), 1) ?>">
            <h3 class="topic"><?= $thread->getTopic() ?></h3>
        </a>
        <div class="info">
            <div class="authors">
            <?php if ($creator != null): ?>
                <div class="creator">created by:<a class="clickable" href="<?= Web\pagelinkUser($creator->getPrimaryKey()) ?>"><?= $creator->getName() ?></a></div>
            <?php endif; ?>
            <?php if ($lastAttr != null): ?>
                <span class="lastAttributor">
                    last: <a class="clickable" href="<?= Web\pagelinkUser($lastAttr->getPrimaryKey()) ?>"><?= $lastAttr->getName() ?></a>
                </span>
            <?php endif; ?>
            </div>
            <div class="indexlink">
                <span class="label">index:</span>
                <div class="threadlink_pagination">
                    <div class='threadlink_pagination'>
                        <?php $lastPag = 0; ?>
                        <?php foreach ($pags as $pag): ?>
                            <?php if (($lastPag + 1) != $pag): ?>
                                <span>...</span>
                            <?php endif; ?>
                            <a href="<?= \Web\pagelinkForumThread($thread->getId(), $pag) ?>"><?= $pag ?></a>
                            <?php $lastPag = $pag; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php endforeach; ?>
