<?php

  /**
   * authorization forms
   * if not logged in: returns login form, and register link
   * if already authorized: return logout form
   */

?>
<div id="authorizationsection">
    <?php
    if (! \Web\Session\Security\Authorizer::userIsAuthorized()) {
        \Web\loadContentView("security/loginform");
        \Web\loadContentView("security/registerlink");
    } else {
        \Web\loadContentView("security/logoutform");
    }
    ?>
</div>
