<?php

/**
 * form with fields:
 *      input_username  (text)
 *      input_password  (password)
 * submit button:
 *      login (submit)

 #TODO inte jättesnyggt med divclass formtable_row etc??
 *
 */

if (!isset($_SESSION['login_errmsg']))
  $_SESSION['login_errmsg']='';

?>
<div>
  <form
      id="loginform"
      method="POST"
      action="<?= htmlentities($_SERVER['REQUEST_URI']); ?>"
      >

    <input type="hidden" name="redirect_url" value="<?= $_SESSION['redirect_url'] ?? '' ?>" />

    <div>
      <span id='login_errmsg'><?= $_SESSION['login_errmsg']; ?></span>
    </div>
    <div class="formtable">
      <div class="formtable_row">
        <label for="input_username">username</label>
      </div>
      <div class="formtable_row">
        <input type="text" id="input_username" name="input_username" required>
      </div>
      <div class="formtable_row">
        <label for="input_password">password</label>
      </div>
      <div class="formtable_row">
        <input type="password" id="input_password" name="input_password" required>
      </div>
      <div class="formtable_row">
        <input type="submit" class="btn" value="login" name="login">
      </div>
    </div>
    <?php \Web\Framework\loadContentView("security/registerlink"); ?>
  </form>
</div>
