<?php $searchresitems = \Database\searchForumUser(getSearchVal());
?>

<ul id="searchres">
<?php foreach($searchresitems as $user): ?>
    <div class="searchres_item">
        <a href="<?= pagelinkUser($user->getPrimaryKey()) ?>">
            <span class="name"><?= $user->getName() ?></span>
            <span class="role"><?= $user->getRole() ?></span>
        </a>
    </div>

<?php endforeach; ?>
</ul>
