
<?php

#TODO tmp lösning
$view_user = \Web\Database\Read::forumUserById(getReqUser());

?>
<div id="admin_tools">
<div class="header">admin tools</div>
<p>OBS denna fungerar inte... se submit button.. den ska ge tooltip</p>
  <form 
      id="admintools"
      method="POST" 
      action="<?php echo htmlentities($_SERVER['PHP_SELF'].'?controller=user'); ?>"
      >
  <table>
    <input type="hidden" name="u" value="<?php echo $view_user->getPrimaryKey(); ?>" />
    <?php if(! $view_user->isAdmin()):
      $bannuser_tooltip = "user is currently: "
      . ($view_user->isBanned()? "true" : "false");
    ?>
    <tr>
    <td>
      <label>banned user</label>
      </td>
      <td>
      <?php
      echo \Web\Helper\toolTip(switchButton("update_user_banned",
        $view_user->isBanned()),
        $bannuser_tooltip);
      ?>
      </td>
    </tr>
    <?php endif; ?>
    <tr>
      <td></td>
      <td>
        <input 
          type="submit" 
          id="submit" 
          class="icon_button material-icons" 
          value="save" 
        name="update_user"></td>
    </tr>
  </table>
</form>
</div>
