<div id="newsfeed">
    <span class="article-header">newsfeed</span>
    <?php
    $news_arr = $data->getNews();
    ?>
    <?php foreach($news_arr as $news): ?>
        <article>
            <div class="newsfeed">
                <h2 class="title"><?= $news->getTitle() ?></h2>
                <div class="created"><?= \Web\Framework\Format::dateTime($news->getCreated()) ?></div>
                <div class="message"><?= $news->getMessage() ?></div>
                <div class="author"><?= $news->getAuthor()->getName() ?></div>
            </div>
        </article>
    <?php endforeach; ?>

</div>
