<article id="forum_content">
    <?php
    $page = getPage();
    \Web\Framework\Factory\Widgets::addToPage('breadcrum', $page);
    ?>
    <h2><?= $data->getHeader() ?></h2>
    <div id="forum_top_bts" class="button_panel">

    </div>
    <div id="forum_content_list">
        <?php $data->getContent(); ?>
    </div>
    <div id="forum_bottom_bts" class="button_panel">

    </div>
    <?php
    #TODO call forum content with AJAX
    if (getSubPage() != 'main') {
        \Web\Framework\Factory\Widgets::addToPage('pagination', $page);
    }

    ?>
</article>