<?php
/**
 * main headcontent
 * @author Mikael Holmbom
 */

?>
<meta charset="utf-8">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<?=
    getScripts(
        "searchsidepanel.js",
        "searchdatabase.js"
    )
    .getStylesheets(
        "authorization.css",
        "elements.css",
        "main.css",
        "message.css",
        "navigation.css",
        "search.css",
        "widgets.css"
    );