<?php 
use Session\Security\Authorizer as Authorizer;
use \Framework\Factory\Widgets;
?>
<div id="banner">
    <div id="header_content">
        <?php \Web\loadContentView("logo", "main"); ?>
    <?php \Web\loadContentView('security/logoutform'); ?>
        <nav>
            <?php \Web\loadContentView("navigation/pagenav", "main"); ?>
            <ul id="user_nav">
                <li><?= getUserNav(\Web\Session\Security\Authorizer::getAuthorizedUser()); ?></li>
            </ul>
        </nav>
    </div>
</div>
<div id="subheader_content">
    <ul id="subheader_left">
        <?php \Web\loadSection("subnav", getPage()); ?>
    </ul>
    <div id="subheader_right">
        <?php \Web\loadContentView("navigation/metanav", "main"); ?>
    </div>
</div>
<?php \Web\Framework\Factory\Widgets::addToPage('searchsidepanel', 'main'); ?>
