<?php 
use Session\Security\Authorizer as Authorizer;
use \Framework\Factory\Widgets;
?>
<div id="banner">
    <div id="header_content">
        <?php loadContentView("logo", "main"); ?>
    <?php
    loadContentView('security/logoutform');
    ?>
        <nav>
            <?php loadContentView("navigation/pagenav", "main"); ?>
            <ul id="user_nav">
                <li><?= getUserNav(Authorizer::getAuthorizedUser()); ?></li>
            </ul>
        </nav>
    </div>
</div>
<div id="subheader_content">
    <ul id="subheader_left">
        <?php loadSection("subnav", getPage()); ?>
    </ul>
    <div id="subheader_right">
        <?php loadContentView("navigation/metanav", "main"); ?>
    </div>
</div>
<?php \Framework\Factory\Widgets::include('searchsidepanel', 'main'); ?>
