<?php
/**
 * defines listeners for handling requests
 * 
 * @author Mikael Holmbom
 * @version 1.0
 */

/**
 * get the current requested page
 */
function getPage() 
{
    return $_REQUEST['page'] ?? '';
}

/**
 * get the current requested subpage
 */
function getSubpage()
{
    return $_REQUEST['subpage'] ?? '';
}

/**
 * get index value from request GET\n
 * param must be >= 0
 * @param index string return value from GET request
 * @return 
 */
function getIndex($key){
    $index = $_REQUEST[$key] ?? '';
    return preg_match("/^[0-9]+$/", $index)
        ? $index
        : null;
}

/**
 * get value from request POST\n
 * scope using this must declare variable $requestIndex
 * @param index return value from GET request 
 * @return 
 */
function post($index){
    global $requestIndex;
    $key = $requestIndex[$index];
    return $_POST[$key] ?? null;
}

/**
 * determine if index is set as GET\n
 * scope using this must declare variable $requestIndex
 * @param index index to determine
 */
function issetGet($index){
    global $requestIndex;
    return isset($_GET[$requestIndex[$index]]);
}

/**
 * determine if index is set as POST\n
 * scope using this must declare variable $requestIndex
 * @param index index to determine
 */
function issetPost($index){
    global $requestIndex;
    return isset($_GET[$requestIndex[$index]]);
}
