<?php

use  \Web\Session\Security\Authorizer as Authorizer;

$authorizedUser = Authorizer::getAuthorizedUser();

$btns = [
    'news'      => $GLOBALS['pagelink']['news'],
    'forum'     => $GLOBALS['pagelink']['forum'],
    'my page'   => \Web\pagelinkUser($authorizedUser)
];

if ($authorizedUser != null && $authorizedUser->isAdmin()) {
    $btns['admin'] = $GLOBALS['pagelink']['admin'];
}

?>

<ul id='page_nav'>
    <?php foreach($btns as $name => $link): ?>
        <?php $extraClass = getPage() == $name ? 'currentpage':''; ?>
        <li>
            <a class="button btn_nav <?= $extraClass ?>" href="<?= $link ?>"><?= $name ?></a>
        </li>
    <?php endforeach; ?>
</ul>
