<?php

use  \Web\Session\Security\Authorizer as Authorizer;

$authorizedUser = Authorizer::getAuthorizedUser();

$user_pk = $authorizedUser == null ? null : $authorizedUser->getPrimaryKey();

$btns = array(
    'news'      => $GLOBALS['pagelink']['news'],
    'forum'     => $GLOBALS['pagelink']['forum'],
    'my page'   => \Web\pagelinkUser($authorizedUser)
);

if ($authorizedUser != null && $authorizedUser->isAdmin())
{
    $btns['admin'] = $GLOBALS['pagelink']['admin'];
}

?>

<ul id='page_nav'>
    <?php foreach($btns as $name => $link): ?>
        <li>
            <?php $extraClass = getPage() == $name? 'current':''?>
            <a class="button btn_nav <?= getPage() == $name? 'currentpage':''?>" href="<?= $link ?>"><?= $name ?></a>
        </li>
    <?php endforeach; ?>
</ul>
