<?php

/**
 * get user navigation ul list
 * if user is null empty string is returned
 * @return string as html
 */
function getUserNav(
    \Web\Database\DAO\ForumUser $user = null
) {
    if ($user == null)
        return "";

    $dropdown_btn =
        "<div class='dropbtn clickable'>"
        .  $user->getName()
        .  "<i class='dropbtn material-icons clickable'>expand_more</i>"
        . "</div>";
    $dropdown_list =
        array(
            "my page" => \Web\pagelinkUser($user)#,
            #"logout" => include "./widgets/security/logoutform.phtml"
        );
    
    return
        \Web\Helper\dropDownList(
            $dropdown_btn,
            $dropdown_list,
            "user_dropdown"
        );
}
