<?php
    \Web\Helper\getScript("confirmation.js")
?>
<form class="delete_post" 
     method="POST" 
     action="<?= htmlentities(\Web\pagelinkPost("deletepost")) ?>"
     onSubmit="return confirmation();" 
    >
    <input type="hidden" name="post" value="<?= $args["post"] ?>" />
    <input type="hidden" name="page_index" value="<?= getPageIndex() ?>" />
    
    <input type="submit" class="icon_button material-icons" value="delete_post" />

</form>
