<?php

Web\Framework\Session\Security\restrictedToAuthorized();

function admintoolsListener(){
    try{
        if ($_SERVER["REQUEST_METHOD"] == "POST") {
            $user = \Web\Database\Read::forumUserById($_POST['user']);

            if ($_POST["update_user"]) {
                 # SET NEW ATTRS
                 $b = null;
                 if(isset($_POST["update_user_banned"]))
                    $b = $_POST["update_user_banned"] == "on" ? 1 : 0;
                 else
                    $b = 0;

                $user->setBanned($b);

                \Web\Database\Update::forumUser($user);
            }
        }

    } catch (RuntimeException $e) {
        echo "could not display user";
    }
}

admintoolsListener();


$reqUserName = getReqUser();
if (empty(trim($reqUserName))) {
    $authorizedUser = Web\Framework\Session\Security\Authorizer::getAuthorizedUser();
    $url = \Web\pagelinkUser($authorizedUser);
    header("Location: $url");
    exit();
}
