<?php

restrictedToAuthorized();

function admintoolsListener(){
    try{
        if ($_SERVER["REQUEST_METHOD"] == "POST") {
            $user = \Database\Read::forumUser($_POST['user']);

            if ($_POST["update_user"]) {
                 # SET NEW ATTRS
                 $b = null;
                 if(isset($_POST["update_user_banned"]))
                    $b = $_POST["update_user_banned"] == "on" ? 1 : 0;
                 else
                    $b = 0;

                $user->setBanned($b);

                \Database\Update::forumUser($user);
            }

            $_GET["u"] = $user->getPrimaryKey();
        }

        $view_user = \Database\Read::forumUser(getReqUser());
    } catch (RuntimeException $e) {
        echo "could not display user";
    }
}

admintoolsListener();

    
