<?php


#TODO if request u is not set, display current user
$reqUser = getReqUser();
if ($reqUser == '') {
    $reqUser = Authorizer::getAuthorizedUser()->getPrimaryKey();
    $url = \Web\pagelinkUser($reqUser);
    header("Location: " . $url);
    exit();
}

$view_user = Web\Database\Read::forumUserById($reqUser);
if ($view_user != null) {
    $subpage = getSubpage() != null ? getSubpage() : 'info';

    \Web\Framework\Factory\Widgets::addToPage($subpage, 'user');

} else {
    throw new \Exception("user was not found");
}
