<?php

use \Web\Session\Security\Authorizer as Authorizer;

$pagelink = $GLOBALS["pagelink"];
$authUser = Authorizer::getAuthorizedUser()->getPrimaryKey();
$view_user = getViewUser();
if ($view_user == null) {
    return;
}

$btnarr = array(
    "info"      => \Web\pagelinkUser($view_user, "info"),
    "stats"     => \Web\pagelinkUser($view_user, "stats")
);

if (getReqUser() == $authUser) {
    $btnarr["settings"] = \Web\pagelinkUser($view_user, "settings");
}

?>

<?php foreach($btnarr as $text => $link): ?>
    <li><a href="<?= $link?>"><?=$text?></a></li>
<?php endforeach; ?>