<?php
use \Web\Framework\Session\Security\Authorizer as Authorizer;

\Web\Framework\Factory\Widgets::addToPage('newsfeed', \Web\Framework\Request\getPage());

?>
<aside>
<?php
    if (! Authorizer::userIsAuthorized()) {
        \Web\Framework\loadContentView('security/loginform');
    }

    #TODO show only if: user is authorized:
    if (Authorizer::userIsAuthorized()) {
    	\Web\Framework\Factory\Widgets::addToPage('latestForumThreads');
    }

?>
</aside>
