<?php
use \Web\Session\Security\Authorizer as Authorizer;

\Web\Framework\Factory\Widgets::addToPage('newsfeed', getPage());

?>
<aside>
    <?php
    if (! Authorizer::userIsAuthorized())
        \Web\loadContentView("security/loginform");

    #TODO show only if: user is authorized:
    if (Authorizer::userIsAuthorized())
    	\Web\Framework\Factory\Widgets::addToPage("latestForumThreads");
    
    ?>
</aside>
