<?php

require_once PATH_ROOT_ABS."database/post.php";

if (isset($_REQUEST["task"])) 
{
    switch($_REQUEST["task"]) {
        case "delete_post":
            \Web\Database\deletePost();
        break;
        case "create_news":
            \Web\Database\createNews();
        break;
        case "create_thread":
            \Web\Database\createThread();
        break;
        case "post_reply":
            \Web\Database\postReply();
        break;
        case "edit_post":
            \Web\Database\editPost();
        break;
        default:
        
        break;
    }
}
