<?php

# modify database
switch (\Web\Framework\getSubpage()) {
    case "deletepost":
        \Web\Database\deletePost();
    break;
    case "news":
        \Web\Framework\Factory\Widgets::addToPage("create_news", "post");
        break;
    case "thread":
    	\Web\Framework\Factory\Widgets::addToPage("create_thread", "post");
    break;
    case "reply":
    	\Web\Framework\Factory\Widgets::addToPage("post_reply", "post");
    break;
    case "editpost":
        \Web\Framework\Factory\Widgets::addToPage("edit_post", "post");
    break;
    default:
    	echo "<h1>error: not found</h1>";
    break;
}
