<?php
echo
    Web\helper\getStylesheet("forum.css")
  . Web\helper\getStylesheet("information.css")
  # read from request and set topic name as this title
  . readTitle();


function readTitle(){
  $title = "forum";
  $topic = NULL;

  try{
    if(getIndex("s") != NULL){
      $topic =
       \Web\Database\Read::subjects(getIndex("s"))[0];
    } elseif (getIndex("t") != NULL){
      $topic =
       \Web\Database\Read::thread(getIndex("t"));
    }
  } catch(RuntimeException $e){

  }

  if($topic != NULL){
      $title .= ":" . $topic->getTopic();
  }
  return Web\helper\setTitle($title);
}
