<?php
use function \Web\Framework\loadContentView;
?>
<div id="forum_top_bts" class="button_panel">
    <?php if (isCurrentMain()): ?>
        
    <?php elseif (isCurrentSubject()): ?>
        <?php loadContentView("create_thread", "forum"); ?>
    <?php elseif (isCurrentThread()): ?>

    <?php endif; ?>
</div>

<?php \Web\Framework\Factory\Widgets::addToPage("forum", \Web\Framework\Request\getPage()); ?>

<div id="forum_bottom_bts" class="button_panel">
    <?php if (isCurrentMain()): ?>

    <?php elseif (isCurrentSubject()): ?>
        
    <?php elseif (isCurrentThread()): ?>
        <?php loadContentView('post_reply', 'forum'); ?>
    <?php endif; ?>
</div>

<?php
if (isCurrentMain()): ?>
    <aside>
        <?php \Web\Framework\Factory\Widgets::addToPage("latestForumThreads"); ?>
    </aside>
<?php endif; ?>
