<?php

use function Web\Framework\Request\getIndex;
use function Web\Framework\Request\getSubpage;

function getThreadIndex()
{
    return getIndex("thread");
}

function getSubjectIndex()
{
    return getIndex("subject");
}

function isCurrentSubject()
{
	return getSubpage() === "subject";
}

function isCurrentThread()
{
	return getSubpage() === "thread";
}

function isCurrentMain()
{
	return getSubpage() === "main";
}

