<?php
namespace Web;
?>
<!DOCTYPE html>
<?php
/*
 * main index file
 * reads controller and redirect to correct page content
 * @author Mikael Holmbom
 * @version 1.0
 */

require_once PATH_ROOT_ABS."database/database.php";
require_once PATH_ROOT_ABS."framework/session/main.php";
require_once PATH_ROOT_ABS."framework/config/settings.php";

try {
    \Web\Framework\Session\start();
    \Web\Database\autoloadDAO();

    include PATH_ROOT_ABS."framework/frontcontroller/data.php";
    include PATH_ROOT_ABS."framework/frontcontroller/view.phtml";

} catch (\Exception $e) {
    echo $e->getMessage();
}
