<?php
namespace Web;
?>
<!DOCTYPE html>
<?php
/*
 * main index file
 * reads controller and redirect to correct page content
 * @author Mikael Holmbom
 * @version 1.0
 */

require_once PATH_ROOT_ABS."database/database.php";
require_once PATH_ROOT_ABS."session/main.phtml";
require_once PATH_ROOT_ABS."session/config/settings.php";


\Web\Session\start();
\Web\Database\autoloadDAO();


include PATH_ROOT_ABS."FrontControllerData.php";
include PATH_ROOT_ABS."FrontControllerView.phtml";
