<?php

if (\Web\Framework\Session\Security\loginListener()) {
    $url = $_SESSION['redirect_url'] ?? $GLOBALS['pagelink']['index'];
    header("Location: $url");
    exit();
}

if (\Web\Framework\Session\Security\Authorizer::userIsAuthorized()) {
    $url = $_SESSION['redirect_url'] ?? $GLOBALS['pagelink']['index'];
    header("Location: $url");
    exit();
}

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    # listen for user register post
    $_SESSION['registeruser_errmsg'] = '';
    if (isset($_POST['user_register'])) {
        $response = \Web\Pages\Register\Helper\register();
        if ($response['success']) {
            echo "SUCCESS";
            $_SESSION["input_name"] = '';
            $_SESSION["input_email"] = '';

            $url = $_SESSION['redirect_url'] ?? $GLOBALS['pagelink']['index'];
            echo "REDIReCT $url";
            header("Location: $url");
            exit();
        } else {
            $_SESSION["registeruser_errmsg"] = $response['message'];
        }
    }
}
