<?php

if (\Session\Security\loginListener()) {
    $pagelink = $GLOBALS['pagelink']['index'];
    header("Location: $pagelink");
    exit();
}

if (\Session\Security\Authorizer::userIsAuthorized()) {
    $pagelink = $GLOBALS['pagelink']['index'];
    header("Location: $pagelink");
    exit();
}

$_SESSION['registeruser_errmsg'] = '';
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    # listen for user register post
    if (isset($_POST['user_register'])) {
        register();
    }
}
