<?php

if (\Web\Session\Security\loginListener()) {
    $url = $_SESSION['redirect_url'] ?? $GLOBALS['pagelink']['index'];
    header("Location: $url");
    exit();
}

if (\Web\Session\Security\Authorizer::userIsAuthorized()) {
    $url = $_SESSION['redirect_url'] ?? $GLOBALS['pagelink']['index'];
    header("Location: $url");
    exit();
}

$_SESSION['registeruser_errmsg'] = '';
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    # listen for user register post
    if (isset($_POST['user_register'])) {
        \Web\Pages\Register\Helper\register();
    }
}
