<?php if(isset($_SESSION["registeruser_errmsg"])): ?>
    <span id="registeruser_errmsg"><?php $_SESSION["registeruser_errmsg"] ?></span>
<?php endif; ?>

<article id="register">
    <?php
    loadContentView(
      "registeruserForm",
      "register"
    );

    loadContentView("validPasswordhint", getPage());
    ?>
</article>

<article id="login">
    <span id="login_h">already a member?</span>
    <?php
    loadContentView("security/loginform");

    ?>
</article>