
<?php foreach ($data->getSubjects() as $subject): ?>
    <div class="forum_content_listitem forum_subject">
        <a href="<?= Web\pagelinkForumSubject($subject->getPrimaryKey())?>">
        <div class="topic"><?= $subject->getTopic() ?></div>
        <div class="info">
            <div class="subtitle"><?= $subject->getSubtitle() ?></div>
        </div>
        </a>
    </div>

<?php endforeach; ?>
